services:
  nginx:
    container_name: nginx
    image: nginx:latest
    working_dir: /var/www
    volumes:
        - ./:/var/www
        - ./vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "80:80"

  db:
    container_name: db
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: test_app
      MYSQL_USER: test_user
      MYSQL_PASSWORD: secret

  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - nginx
      - db

volumes:
    db_data:

